export type CategoryRule = { category: string; words: string[] };

export const CATEGORY_RULES: CategoryRule[] = [
  {
    category: "Frukt & grönt",
    words: [
      "ananas",
    "apelsin",
    "blodapelsin",
    "aprikos",
    "aubergine",
    "avokado",
    "banan",
    "blekselleri",
    "stjälkselleri",
    "blomkål",
    "bondböna",
    "broccoli",
    "brysselkål",
    "rosenkål",
    "brytböna",
    "champinjon",
    "chili",
    "citron",
    "endiv",
    "fänkål",
    "granatäpple",
    "grapefrukt",
    "grönkål",
    "gul lök",
    "gurka",
    "ingefära",
    "jordärtskocka",
    "kaktusfikon",
    "kinakål",
    "salladskål",
    "kiwi",
    "klementin",
    "kronärtskocka",
    "kryddkrasse",
    "smörgåskrasse",
    "kålrabbi",
    "kålrot",
    "lime",
    "majrova",
    "majs",
    "mandarin",
    "mango",
    "mangold",
    "melon",
    "morot",
    "morötter",
    "nektarin",
    "pak choy",
    "palmkål",
    "svartkål",
    "palsternacka",
    "paprika",
    "pepparrot",
    "persika",
    "persilja",
    "potatis",
    "pumpa",
    "purjolök",
    "päron",
    "radicchio",
    "rosensallat",
    "ramiro",
    "romanesco",
    "rotpersilja",
    "persiljerot",
    "rotselleri",
    "rucola",
    "rädisa",
    "rödbeta",
    "rödkål",
    "rödlök",
    "salladslök",
    "piplök",
    "sallat",
    "savojkål",
    "schalottenlök",
    "skärböna",
    "sparris",
    "spenat",
    "spetskål",
    "sugar snaps",
    "svartrot",
    "sötpotatis",
    "timjan",
    "tomat",
    "vattenkrasse",
    "vaxböna",
    "vindruva",
    "vitkål",
    "vitlök",
    "zucchini",
    "äpple",
    ],
  },
  {
    category: "Mejeri",
    words: [
      "mjölk","laktosfri mjölk","fil","yoghurt","grekisk yoghurt","kvarg",
      "grädde","matlagningsgrädde","vispgrädde",
      "crème fraiche","creme fraiche","gräddfil","turkisk yoghurt",
      "smör","bregott","margarin",
      "ost","riven ost","mozzarella","feta","halloumi","parmesan","cheddar",
      "keso","ricotta",
      "ägg",
    ],
  },
  {
    category: "Kött",
    words: [
      "kött","nöt","nötkött","fläsk","fläskkött","lamm",
      "kyckling","kalkon",
      "färs","blandfärs","nötfärs","fläskfärs",
      "korv","falukorv","chorizo","prinskorv",
      "bacon","skinka","salami","pålägg",
      "köttbull","hamburg","biff","entrecote","kotlett","revben",
    ],
  },
  {
    category: "Fisk & skaldjur",
    words: [
      "fisk","lax","torsk","sej","kolja","makrill","sill","strömming",
      "tonfisk","räka","räkor","kräft","krabba","mussla","bläckfisk",
      "fiskpinnar","surimi",
      "rom","kaviar",
    ],
  },
  {
    category: "Bröd & spannmål",
    words: [
      "bröd","limpa","fralla","bulle","baguette","pitabröd","tortilla","wrap",
      "korvbröd","hamburgerbröd",
      "knäckebröd","skorpor","kex",
      "pasta","spaghetti","makaron","penne","fusilli",
      "ris","basmatiris","jasminris","råris",
      "mjöl","vetemjöl","rågmjöl","dinkel","havre",
      "gryn","havregryn","mannagryn",
      "couscous","bulgur","quinoa",
      "müsli","granola"
    ],
  },
  {
    category: "Pålägg & frukost",
    words: [
      "skinka","ost","leverpastej","kaviar","messmör",
      "sylt","marmelad","honung","nutella",
      "jordnötssmör","peanut butter",
      "flingor","cornflakes",
    ],
  },
  {
    category: "Konserver & torrvaror",
    words: [
      "krossade tomater","tomatpuré","passata",
      "bönor","kidneybönor","svarta bönor","kikärtor","linser",
      "majs på burk","tonfisk på burk",
      "buljong","fond",
      "pasta","ris","nudlar",
      "mjöl","socker","salt","peppar",
      "bakpulver","vaniljsocker","jäst",
      "tacoskal","tacokrydda",
    ],
  },
  {
    category: "Kryddor & såser",
    words: [
      "ketchup","senap","majonnäs","aioli",
      "soja","teriyaki","sweet chili","chilisås",
      "sriracha","tabasco",
      "vinäger","balsamvinäger",
      "olja","olivolja","rapsolja",
      "dressing","pesto",
      "tacosås","salsa",
    ],
  },
  {
    category: "Snacks, godis & läsk",
    words: [
      "chips","cheez","ostbågar","snacks","nötter","mandel","cashew","jordnöt",
      "popcorn",
      "godis","choklad","kexchoklad","gele","lakrits","tablett",
      "glass","klubba",
      "läsk","cola","pepsi","coca-cola","fanta","sprite",
      "energydryck","red bull",
      "saft","juice","läskeblask",
    ],
  },
  {
    category: "Frys",
    words: [
      "fryst","frysta","djupfryst",
      "frysta grönsaker","frysta bär",
      "glass","fryst pizza","fiskpinnar"
    ],
  },
  {
    category: "Hygien & hushåll",
    words: [
      "toapapper","hushållspapper","papper",
      "diskmedel","tvättmedel","sköljmedel",
      "tandkräm","tandborste","schampo","balsam","tvål",
      "deodorant",
    ],
  },
];
